# Generated by Django 5.0.2 on 2024-02-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6),
        ),
    ]
